version: '3.8'
services:
  ui:
    image: loan-calculator-ui:latest
    ports:
      - "80:80"
    environment:
      SERVICE_URL: http://api:5000/loancalculator
    depends_on:
      - api

  api:
    image: loan-calculator-api:latest
    ports:
      - "5000:5000"
    environment:
      STORE_URL: http://data:5000/store 
      RETRIEVE_URL: http://data:5000/retrieve 
      TEST_URL: http://data:5000/test
    depends_on:
      - data

  data:
    image: loan-calculator-data:latest
    ports:
      - "5050:5000"
    depends_on:
      - memcached

  memcached:
    image: bitnami/memcached:latest
    ports:
      - "11211:11211"
    #command: ["-m", "64"]
    #restart: always


    
    